[package]
name = "monocle_host"
version = "0.1.0"
authors = ["TheZoq2 <frans.skarman@gmail.com>"]

[profile.dev]
debug-assertions=false

[dependencies]
serial = "0.4.0"
api = {path = "../api"}
ssmarshal = {version = "1.0", default-features = false}
